sudo: required
dist: trusty
group: beta
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - rpm
cache:
  directories:
    - $HOME/.m2
services:
  - docker
script:
  - mvn test verify -Dmaven.javadoc.skip=true -B -V
before_deploy:
  - find . -type f -name 'original-*.jar' -delete
  - mvn jdeb:jdeb
  - mvn rpm:rpm
deploy:
  provider: releases
  api_key:
    secure: "Eo4JW7QRGOliWj2JvEyA3pUip1CctdjMKrjf0M99DU3Dz/weex/Gs0C75HM/97HmEr5924wpJANCbNaf+9qM813MVdD96S2EmBJiMYioL5Br1Mb3zALSIPd+O9B/VPmKE9Nx9z1lcsGhTR1xllc4v2b8KI1ucfAft8c6+ewKALFKF2vgj50Md4B/I8fECeRJ8Y5PrcnwZSQE7/8IwRQBL/DK8qoOtjl07AKls+cl+4tMlSDinMPkQ1Yte9B8A9V5+gAJve9giexSf3FjltfyI/xvy49SGbG35sRX7TqKxI4upxoYtnfe+SBUbMT4dDoMhPdOhDQqFXViFXxL+U2TBMXXdN3KUcPsdhBA1epxTk87KxCtx4DSIA+NG6eVM3ch7U1k8jSSE2Jh/LTlFq585EhZJa6L7R2iVfJKlqeHYDqoGKpQm6TH+KgogB3LKaU33QcpXtcWk4m6LPZdWe/6UtLtWdK5KngWd+Xl4spa8aYzhnuWGED7hbtj8qIA5RGukgS6cOzfXGOy3AXGtlTWLT/TvJMY3IuKZF+ireMR6+BbyTrouV2FRweJa5K/QHk4ZihjykSeXeC/87GJVFxI49qRQxKOkNrD6eOXnaujasa+r5yQrCv4LQZEF0dOJ4ZkHpG1EcN0j1Ek5TDVBE3Fy8N+AHsMu4JXKv2EmZjaQ3E="
  file_glob: true
  file:
    - "**/target/*.jar"
    - "**/target/*.deb"
    - "**/target/**/*.rpm"
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk8
